### ISSUE TITLE
自定义配置和自定义软件没看太懂

### ISSUE THREAD

**Issue by coLATin** [ryohuang/slim-wrt#3]
本地直接就一键编译了....
自定义软件是加在slim-wrt/downloaded/openwrt-19.07-d5ae565/feeds.conf.default这个官方源的软件配置文件里呢
还是clone三方的软件包到slimapps目录下？
另外make menuconfig做自定义配置也是要到openwrt-19.07-d5ae565去配置还是要怎么配置，没看明白，望补充下，谢谢

**Comment by ryohuang** [comment]
嗯，感谢关注。之后会补充针对开发者的文档。

**Comment by ryohuang** [comment]
自定义软件分两种情况。
一种是目录结构良好的，见： https://github.com/ryohuang/slim-wrt/blob/master/patches-modules/0000-common-configs/custom.sh
另一种是在某个项目中存在于一大堆软件中的，我选择把它拷贝过来。 见https://github.com/ryohuang/slim-wrt/tree/master/slimapps/application 下的luci-app-filetransfer， 这个就是我从lean的仓库拷贝过来的。
slimapps/application 也是我用来自己写一些程序的地方，比如taghost和boostupnp。

make menuconfig如果想手动执行的话，需要到具体的workpath。如果profile是slim那么应该到slim-src下执行。

**Comment by NagaseKouichi** [comment]
是需要在本地跑一遍make SLIM_CFG_PROFILE=slim showtime，才会有slim-src目录，然后进slim-src目录去运行make menuconfig来生成config文件，替换/profiles/slim/下面的config文件，然后再运行make SLIM_CFG_PROFILE=slim encore是吗？

如果我要在脚本里面下载自定义软件的源码，是在/patches-modules/0000-common-configs/custom.sh文件里面，加上
git clone https://github.com/tty228/luci-app-serverchan.git slimapps/application/luci-app-serverchan
这样吗？

**Comment by ryohuang** [comment]
> 是需要在本地跑一遍make SLIM_CFG_PROFILE=slim showtime，才会有slim-src目录，然后进slim-src目录去运行make menuconfig来生成config文件，替换/profiles/slim/下面的config文件，然后再运行make SLIM_CFG_PROFILE=slim encore是吗？
> 
> 如果我要在脚本里面下载自定义软件的源码，是在/patches-modules/0000-common-configs/custom.sh文件里面，加上
> git clone https://github.com/tty228/luci-app-serverchan.git slimapps/application/luci-app-serverchan
> 这样吗？

如果你想定义自己的profile的话，建议你新建一个，而不是修改已有的profile。已有的profile可以作为一个参考模板。
https://github.com/ryohuang/slim-wrt/blob/master/Makefile 这个里面你可以看看整个流程是怎么样的，比如什么时候生成
slim-src


serverchan的话，我更建议参考https://github.com/ryohuang/slim-wrt/tree/master/patches-modules/0001-fullcone-nat/openwrt-fullconenat 的做法 （这个好用吗？好用我也试试）
